name: tg
description: Telegram Client API (MTProto) to connect to Telegram and control a user programmatically.
version: 0.0.12
homepage: https://pwa.ir
repository: https://github.com/telegramflutter/tg
publish_to: none
topics:
 - telegram
 - tdlib
 
environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # t: ^0.0.26
  t:
    git:
      url: https://github.com/aoteowner/t
      ref: 33671eb88
  archive: ^4.0.7
  pointycastle: ^4.0.0

dependency_overrides:
  t:
    path: ../t

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
